/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/applicant/BPAM/AncillaryPermits/Architectural': RouteRecordInfo<'/applicant/BPAM/AncillaryPermits/Architectural', '/applicant/BPAM/AncillaryPermits/Architectural', Record<never, never>, Record<never, never>>,
    '/applicant/BPAM/AncillaryPermits/Civilstructural': RouteRecordInfo<'/applicant/BPAM/AncillaryPermits/Civilstructural', '/applicant/BPAM/AncillaryPermits/Civilstructural', Record<never, never>, Record<never, never>>,
    '/applicant/BPAM/AncillaryPermits/Electrical': RouteRecordInfo<'/applicant/BPAM/AncillaryPermits/Electrical', '/applicant/BPAM/AncillaryPermits/Electrical', Record<never, never>, Record<never, never>>,
    '/applicant/BPAM/AncillaryPermits/Electronics': RouteRecordInfo<'/applicant/BPAM/AncillaryPermits/Electronics', '/applicant/BPAM/AncillaryPermits/Electronics', Record<never, never>, Record<never, never>>,
    '/applicant/BPAM/AncillaryPermits/Mechanical': RouteRecordInfo<'/applicant/BPAM/AncillaryPermits/Mechanical', '/applicant/BPAM/AncillaryPermits/Mechanical', Record<never, never>, Record<never, never>>,
    '/applicant/BPAM/AncillaryPermits/Plumbing': RouteRecordInfo<'/applicant/BPAM/AncillaryPermits/Plumbing', '/applicant/BPAM/AncillaryPermits/Plumbing', Record<never, never>, Record<never, never>>,
    '/applicant/BPAM/AncillaryPermits/Sanitary': RouteRecordInfo<'/applicant/BPAM/AncillaryPermits/Sanitary', '/applicant/BPAM/AncillaryPermits/Sanitary', Record<never, never>, Record<never, never>>,
    '/applicant/BPAM/AncillaryPermits/UnifiedApplicationForm': RouteRecordInfo<'/applicant/BPAM/AncillaryPermits/UnifiedApplicationForm', '/applicant/BPAM/AncillaryPermits/UnifiedApplicationForm', Record<never, never>, Record<never, never>>,
    '/applicant/BPAM/UnifiedForm/AncillaryForms': RouteRecordInfo<'/applicant/BPAM/UnifiedForm/AncillaryForms', '/applicant/BPAM/UnifiedForm/AncillaryForms', Record<never, never>, Record<never, never>>,
    '/applicant/BPAM/UnifiedForm/ApplicantInformation': RouteRecordInfo<'/applicant/BPAM/UnifiedForm/ApplicantInformation', '/applicant/BPAM/UnifiedForm/ApplicantInformation', Record<never, never>, Record<never, never>>,
    '/applicant/BPAM/UnifiedForm/BPADetails': RouteRecordInfo<'/applicant/BPAM/UnifiedForm/BPADetails', '/applicant/BPAM/UnifiedForm/BPADetails', Record<never, never>, Record<never, never>>,
    '/applicant/BPAM/UnifiedForm/ConstructionInformation': RouteRecordInfo<'/applicant/BPAM/UnifiedForm/ConstructionInformation', '/applicant/BPAM/UnifiedForm/ConstructionInformation', Record<never, never>, Record<never, never>>,
    '/applicant/BPAM/UnifiedForm/CoOccupancy': RouteRecordInfo<'/applicant/BPAM/UnifiedForm/CoOccupancy', '/applicant/BPAM/UnifiedForm/CoOccupancy', Record<never, never>, Record<never, never>>,
    '/applicant/BPAM/UnifiedForm/Navigation': RouteRecordInfo<'/applicant/BPAM/UnifiedForm/Navigation', '/applicant/BPAM/UnifiedForm/Navigation', Record<never, never>, Record<never, never>>,
    '/applicant/BPAM/UnifiedForm/PlanUpload': RouteRecordInfo<'/applicant/BPAM/UnifiedForm/PlanUpload', '/applicant/BPAM/UnifiedForm/PlanUpload', Record<never, never>, Record<never, never>>,
    '/applicant/BPAM/UnifiedForm/Signatories': RouteRecordInfo<'/applicant/BPAM/UnifiedForm/Signatories', '/applicant/BPAM/UnifiedForm/Signatories', Record<never, never>, Record<never, never>>,
    '/applicant/Homepage': RouteRecordInfo<'/applicant/Homepage', '/applicant/Homepage', Record<never, never>, Record<never, never>>,
    '/applicant/OPAM/OPapplication/Opapply': RouteRecordInfo<'/applicant/OPAM/OPapplication/Opapply', '/applicant/OPAM/OPapplication/Opapply', Record<never, never>, Record<never, never>>,
    '/applicant/OPAM/OPapplication/Oploaction': RouteRecordInfo<'/applicant/OPAM/OPapplication/Oploaction', '/applicant/OPAM/OPapplication/Oploaction', Record<never, never>, Record<never, never>>,
    '/applicant/OPAM/OPapplication/OPowner': RouteRecordInfo<'/applicant/OPAM/OPapplication/OPowner', '/applicant/OPAM/OPapplication/OPowner', Record<never, never>, Record<never, never>>,
    '/applicant/OPAM/OPapplication/OPportal': RouteRecordInfo<'/applicant/OPAM/OPapplication/OPportal', '/applicant/OPAM/OPapplication/OPportal', Record<never, never>, Record<never, never>>,
    '/applicant/OPAM/OPapplication/OPsignatories': RouteRecordInfo<'/applicant/OPAM/OPapplication/OPsignatories', '/applicant/OPAM/OPapplication/OPsignatories', Record<never, never>, Record<never, never>>,
    '/applicant/OPAM/OPapplication/OPtype': RouteRecordInfo<'/applicant/OPAM/OPapplication/OPtype', '/applicant/OPAM/OPapplication/OPtype', Record<never, never>, Record<never, never>>,
    '/applicant/OPAM/OPforms/Completion': RouteRecordInfo<'/applicant/OPAM/OPforms/Completion', '/applicant/OPAM/OPforms/Completion', Record<never, never>, Record<never, never>>,
    '/applicant/OPAM/OPforms/Electrical': RouteRecordInfo<'/applicant/OPAM/OPforms/Electrical', '/applicant/OPAM/OPforms/Electrical', Record<never, never>, Record<never, never>>,
    '/applicant/OPAM/OPforms/FormsSection': RouteRecordInfo<'/applicant/OPAM/OPforms/FormsSection', '/applicant/OPAM/OPforms/FormsSection', Record<never, never>, Record<never, never>>,
    '/applicant/OPAM/OPforms/Unified': RouteRecordInfo<'/applicant/OPAM/OPforms/Unified', '/applicant/OPAM/OPforms/Unified', Record<never, never>, Record<never, never>>,
    '/auth/ForgotPW': RouteRecordInfo<'/auth/ForgotPW', '/auth/ForgotPW', Record<never, never>, Record<never, never>>,
    '/auth/Login': RouteRecordInfo<'/auth/Login', '/auth/Login', Record<never, never>, Record<never, never>>,
    '/ForgotPW': RouteRecordInfo<'/ForgotPW', '/ForgotPW', Record<never, never>, Record<never, never>>,
    '/landing-page/LandingPage': RouteRecordInfo<'/landing-page/LandingPage', '/landing-page/LandingPage', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/LoginAuth': RouteRecordInfo<'/LoginAuth', '/LoginAuth', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/applicant/BPAM/AncillaryPermits/Architectural.vue': {
      routes: '/applicant/BPAM/AncillaryPermits/Architectural'
      views: never
    }
    'src/pages/applicant/BPAM/AncillaryPermits/Civilstructural.vue': {
      routes: '/applicant/BPAM/AncillaryPermits/Civilstructural'
      views: never
    }
    'src/pages/applicant/BPAM/AncillaryPermits/Electrical.vue': {
      routes: '/applicant/BPAM/AncillaryPermits/Electrical'
      views: never
    }
    'src/pages/applicant/BPAM/AncillaryPermits/Electronics.vue': {
      routes: '/applicant/BPAM/AncillaryPermits/Electronics'
      views: never
    }
    'src/pages/applicant/BPAM/AncillaryPermits/Mechanical.vue': {
      routes: '/applicant/BPAM/AncillaryPermits/Mechanical'
      views: never
    }
    'src/pages/applicant/BPAM/AncillaryPermits/Plumbing.vue': {
      routes: '/applicant/BPAM/AncillaryPermits/Plumbing'
      views: never
    }
    'src/pages/applicant/BPAM/AncillaryPermits/Sanitary.vue': {
      routes: '/applicant/BPAM/AncillaryPermits/Sanitary'
      views: never
    }
    'src/pages/applicant/BPAM/AncillaryPermits/UnifiedApplicationForm.vue': {
      routes: '/applicant/BPAM/AncillaryPermits/UnifiedApplicationForm'
      views: never
    }
    'src/pages/applicant/BPAM/UnifiedForm/AncillaryForms.vue': {
      routes: '/applicant/BPAM/UnifiedForm/AncillaryForms'
      views: never
    }
    'src/pages/applicant/BPAM/UnifiedForm/ApplicantInformation.vue': {
      routes: '/applicant/BPAM/UnifiedForm/ApplicantInformation'
      views: never
    }
    'src/pages/applicant/BPAM/UnifiedForm/BPADetails.vue': {
      routes: '/applicant/BPAM/UnifiedForm/BPADetails'
      views: never
    }
    'src/pages/applicant/BPAM/UnifiedForm/ConstructionInformation.vue': {
      routes: '/applicant/BPAM/UnifiedForm/ConstructionInformation'
      views: never
    }
    'src/pages/applicant/BPAM/UnifiedForm/CoOccupancy.vue': {
      routes: '/applicant/BPAM/UnifiedForm/CoOccupancy'
      views: never
    }
    'src/pages/applicant/BPAM/UnifiedForm/Navigation.vue': {
      routes: '/applicant/BPAM/UnifiedForm/Navigation'
      views: never
    }
    'src/pages/applicant/BPAM/UnifiedForm/PlanUpload.vue': {
      routes: '/applicant/BPAM/UnifiedForm/PlanUpload'
      views: never
    }
    'src/pages/applicant/BPAM/UnifiedForm/Signatories.vue': {
      routes: '/applicant/BPAM/UnifiedForm/Signatories'
      views: never
    }
    'src/pages/applicant/Homepage.vue': {
      routes: '/applicant/Homepage'
      views: never
    }
    'src/pages/applicant/OPAM/OPapplication/Opapply.vue': {
      routes: '/applicant/OPAM/OPapplication/Opapply'
      views: never
    }
    'src/pages/applicant/OPAM/OPapplication/Oploaction.vue': {
      routes: '/applicant/OPAM/OPapplication/Oploaction'
      views: never
    }
    'src/pages/applicant/OPAM/OPapplication/OPowner.vue': {
      routes: '/applicant/OPAM/OPapplication/OPowner'
      views: never
    }
    'src/pages/applicant/OPAM/OPapplication/OPportal.vue': {
      routes: '/applicant/OPAM/OPapplication/OPportal'
      views: never
    }
    'src/pages/applicant/OPAM/OPapplication/OPsignatories.vue': {
      routes: '/applicant/OPAM/OPapplication/OPsignatories'
      views: never
    }
    'src/pages/applicant/OPAM/OPapplication/OPtype.vue': {
      routes: '/applicant/OPAM/OPapplication/OPtype'
      views: never
    }
    'src/pages/applicant/OPAM/OPforms/Completion.vue': {
      routes: '/applicant/OPAM/OPforms/Completion'
      views: never
    }
    'src/pages/applicant/OPAM/OPforms/Electrical.vue': {
      routes: '/applicant/OPAM/OPforms/Electrical'
      views: never
    }
    'src/pages/applicant/OPAM/OPforms/FormsSection.vue': {
      routes: '/applicant/OPAM/OPforms/FormsSection'
      views: never
    }
    'src/pages/applicant/OPAM/OPforms/Unified.vue': {
      routes: '/applicant/OPAM/OPforms/Unified'
      views: never
    }
    'src/pages/auth/ForgotPW.vue': {
      routes: '/auth/ForgotPW'
      views: never
    }
    'src/pages/auth/Login.vue': {
      routes: '/auth/Login'
      views: never
    }
    'src/pages/ForgotPW.vue': {
      routes: '/ForgotPW'
      views: never
    }
    'src/pages/landing-page/LandingPage.vue': {
      routes: '/landing-page/LandingPage'
      views: never
    }
    'src/pages/Login.vue': {
      routes: '/Login'
      views: never
    }
    'src/pages/LoginAuth.vue': {
      routes: '/LoginAuth'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
