/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Applicant-bpInquiry': RouteRecordInfo<'/Applicant-bpInquiry', '/Applicant-bpInquiry', Record<never, never>, Record<never, never>>,
    '/Applicant-ForgotPW': RouteRecordInfo<'/Applicant-ForgotPW', '/Applicant-ForgotPW', Record<never, never>, Record<never, never>>,
    '/Applicant-Homepage': RouteRecordInfo<'/Applicant-Homepage', '/Applicant-Homepage', Record<never, never>, Record<never, never>>,
    '/Applicant-Login': RouteRecordInfo<'/Applicant-Login', '/Applicant-Login', Record<never, never>, Record<never, never>>,
    '/Applicant-opInquiry': RouteRecordInfo<'/Applicant-opInquiry', '/Applicant-opInquiry', Record<never, never>, Record<never, never>>,
    '/Applicant-Registration': RouteRecordInfo<'/Applicant-Registration', '/Applicant-Registration', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/Applicant-bpInquiry.vue': {
      routes: '/Applicant-bpInquiry'
      views: never
    }
    'src/pages/Applicant-ForgotPW.vue': {
      routes: '/Applicant-ForgotPW'
      views: never
    }
    'src/pages/Applicant-Homepage.vue': {
      routes: '/Applicant-Homepage'
      views: never
    }
    'src/pages/Applicant-Login.vue': {
      routes: '/Applicant-Login'
      views: never
    }
    'src/pages/Applicant-opInquiry.vue': {
      routes: '/Applicant-opInquiry'
      views: never
    }
    'src/pages/Applicant-Registration.vue': {
      routes: '/Applicant-Registration'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
