/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsCard: typeof import('./src/components/StatsCard.vue')['default']
  }
}
