/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Admin/BPAM/AAapproval/Administrative': RouteRecordInfo<'/Admin/BPAM/AAapproval/Administrative', '/Admin/BPAM/AAapproval/Administrative', Record<never, never>, Record<never, never>>,
    '/Admin/BPAM/AAapproval/ApprovedPlans': RouteRecordInfo<'/Admin/BPAM/AAapproval/ApprovedPlans', '/Admin/BPAM/AAapproval/ApprovedPlans', Record<never, never>, Record<never, never>>,
    '/Admin/BPAM/OboHead/EvaluatedPlans': RouteRecordInfo<'/Admin/BPAM/OboHead/EvaluatedPlans', '/Admin/BPAM/OboHead/EvaluatedPlans', Record<never, never>, Record<never, never>>,
    '/Admin/BPAM/OboHead/ListApproval': RouteRecordInfo<'/Admin/BPAM/OboHead/ListApproval', '/Admin/BPAM/OboHead/ListApproval', Record<never, never>, Record<never, never>>,
    '/Admin/BPAM/PlanEvaluator/ListPlan': RouteRecordInfo<'/Admin/BPAM/PlanEvaluator/ListPlan', '/Admin/BPAM/PlanEvaluator/ListPlan', Record<never, never>, Record<never, never>>,
    '/Admin/BPAM/PlanEvaluator/PlanEvaluation': RouteRecordInfo<'/Admin/BPAM/PlanEvaluator/PlanEvaluation', '/Admin/BPAM/PlanEvaluator/PlanEvaluation', Record<never, never>, Record<never, never>>,
    '/Admin/BPAM/PlanEvaluator/PlanInformation': RouteRecordInfo<'/Admin/BPAM/PlanEvaluator/PlanInformation', '/Admin/BPAM/PlanEvaluator/PlanInformation', Record<never, never>, Record<never, never>>,
    '/Admin/CMM/Compliance/compliance': RouteRecordInfo<'/Admin/CMM/Compliance/compliance', '/Admin/CMM/Compliance/compliance', Record<never, never>, Record<never, never>>,
    '/Admin/CMM/RQMonitoring/rqmonitoring': RouteRecordInfo<'/Admin/CMM/RQMonitoring/rqmonitoring', '/Admin/CMM/RQMonitoring/rqmonitoring', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/AAverification/AAchecklist': RouteRecordInfo<'/Admin/OPAM/AAverification/AAchecklist', '/Admin/OPAM/AAverification/AAchecklist', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/AAverification/AAdashboard': RouteRecordInfo<'/Admin/OPAM/AAverification/AAdashboard', '/Admin/OPAM/AAverification/AAdashboard', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/AAverification/tabs/Checklist': RouteRecordInfo<'/Admin/OPAM/AAverification/tabs/Checklist', '/Admin/OPAM/AAverification/tabs/Checklist', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/ApplicantDetails': RouteRecordInfo<'/Admin/OPAM/ApplicantDetails', '/Admin/OPAM/ApplicantDetails', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/BIinspection/BIdashboard': RouteRecordInfo<'/Admin/OPAM/BIinspection/BIdashboard', '/Admin/OPAM/BIinspection/BIdashboard', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/BIinspection/BIreport': RouteRecordInfo<'/Admin/OPAM/BIinspection/BIreport', '/Admin/OPAM/BIinspection/BIreport', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/BIinspection/CIdashboard': RouteRecordInfo<'/Admin/OPAM/BIinspection/CIdashboard', '/Admin/OPAM/BIinspection/CIdashboard', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/BIinspection/CIreport': RouteRecordInfo<'/Admin/OPAM/BIinspection/CIreport', '/Admin/OPAM/BIinspection/CIreport', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/BIinspection/tabs/InspectionReportTab': RouteRecordInfo<'/Admin/OPAM/BIinspection/tabs/InspectionReportTab', '/Admin/OPAM/BIinspection/tabs/InspectionReportTab', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/BIinspection/tabs/PdfPlansTab': RouteRecordInfo<'/Admin/OPAM/BIinspection/tabs/PdfPlansTab', '/Admin/OPAM/BIinspection/tabs/PdfPlansTab', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/BIinspection/tabs/ReportSummaryTab': RouteRecordInfo<'/Admin/OPAM/BIinspection/tabs/ReportSummaryTab', '/Admin/OPAM/BIinspection/tabs/ReportSummaryTab', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/TSscheduling/modal/SchedulingModal': RouteRecordInfo<'/Admin/OPAM/TSscheduling/modal/SchedulingModal', '/Admin/OPAM/TSscheduling/modal/SchedulingModal', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/TSscheduling/tabs/ChecklistTab': RouteRecordInfo<'/Admin/OPAM/TSscheduling/tabs/ChecklistTab', '/Admin/OPAM/TSscheduling/tabs/ChecklistTab', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/TSscheduling/tabs/InspectionScheduleTab': RouteRecordInfo<'/Admin/OPAM/TSscheduling/tabs/InspectionScheduleTab', '/Admin/OPAM/TSscheduling/tabs/InspectionScheduleTab', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/TSscheduling/TSdashboard': RouteRecordInfo<'/Admin/OPAM/TSscheduling/TSdashboard', '/Admin/OPAM/TSscheduling/TSdashboard', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/TSscheduling/TSinspection': RouteRecordInfo<'/Admin/OPAM/TSscheduling/TSinspection', '/Admin/OPAM/TSscheduling/TSinspection', Record<never, never>, Record<never, never>>,
    '/auth/Login': RouteRecordInfo<'/auth/Login', '/auth/Login', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/Admin/BPAM/AAapproval/Administrative.vue': {
      routes: '/Admin/BPAM/AAapproval/Administrative'
      views: never
    }
    'src/pages/Admin/BPAM/AAapproval/ApprovedPlans.vue': {
      routes: '/Admin/BPAM/AAapproval/ApprovedPlans'
      views: never
    }
    'src/pages/Admin/BPAM/OboHead/EvaluatedPlans.vue': {
      routes: '/Admin/BPAM/OboHead/EvaluatedPlans'
      views: never
    }
    'src/pages/Admin/BPAM/OboHead/ListApproval.vue': {
      routes: '/Admin/BPAM/OboHead/ListApproval'
      views: never
    }
    'src/pages/Admin/BPAM/PlanEvaluator/ListPlan.vue': {
      routes: '/Admin/BPAM/PlanEvaluator/ListPlan'
      views: never
    }
    'src/pages/Admin/BPAM/PlanEvaluator/PlanEvaluation.vue': {
      routes: '/Admin/BPAM/PlanEvaluator/PlanEvaluation'
      views: never
    }
    'src/pages/Admin/BPAM/PlanEvaluator/PlanInformation.vue': {
      routes: '/Admin/BPAM/PlanEvaluator/PlanInformation'
      views: never
    }
    'src/pages/Admin/CMM/Compliance/compliance.vue': {
      routes: '/Admin/CMM/Compliance/compliance'
      views: never
    }
    'src/pages/Admin/CMM/RQMonitoring/rqmonitoring.vue': {
      routes: '/Admin/CMM/RQMonitoring/rqmonitoring'
      views: never
    }
    'src/pages/Admin/OPAM/AAverification/AAchecklist.vue': {
      routes: '/Admin/OPAM/AAverification/AAchecklist'
      views: never
    }
    'src/pages/Admin/OPAM/AAverification/AAdashboard.vue': {
      routes: '/Admin/OPAM/AAverification/AAdashboard'
      views: never
    }
    'src/pages/Admin/OPAM/AAverification/tabs/Checklist.vue': {
      routes: '/Admin/OPAM/AAverification/tabs/Checklist'
      views: never
    }
    'src/pages/Admin/OPAM/ApplicantDetails.vue': {
      routes: '/Admin/OPAM/ApplicantDetails'
      views: never
    }
    'src/pages/Admin/OPAM/BIinspection/BIdashboard.vue': {
      routes: '/Admin/OPAM/BIinspection/BIdashboard'
      views: never
    }
    'src/pages/Admin/OPAM/BIinspection/BIreport.vue': {
      routes: '/Admin/OPAM/BIinspection/BIreport'
      views: never
    }
    'src/pages/Admin/OPAM/BIinspection/CIdashboard.vue': {
      routes: '/Admin/OPAM/BIinspection/CIdashboard'
      views: never
    }
    'src/pages/Admin/OPAM/BIinspection/CIreport.vue': {
      routes: '/Admin/OPAM/BIinspection/CIreport'
      views: never
    }
    'src/pages/Admin/OPAM/BIinspection/tabs/InspectionReportTab.vue': {
      routes: '/Admin/OPAM/BIinspection/tabs/InspectionReportTab'
      views: never
    }
    'src/pages/Admin/OPAM/BIinspection/tabs/PdfPlansTab.vue': {
      routes: '/Admin/OPAM/BIinspection/tabs/PdfPlansTab'
      views: never
    }
    'src/pages/Admin/OPAM/BIinspection/tabs/ReportSummaryTab.vue': {
      routes: '/Admin/OPAM/BIinspection/tabs/ReportSummaryTab'
      views: never
    }
    'src/pages/Admin/OPAM/TSscheduling/modal/SchedulingModal.vue': {
      routes: '/Admin/OPAM/TSscheduling/modal/SchedulingModal'
      views: never
    }
    'src/pages/Admin/OPAM/TSscheduling/tabs/ChecklistTab.vue': {
      routes: '/Admin/OPAM/TSscheduling/tabs/ChecklistTab'
      views: never
    }
    'src/pages/Admin/OPAM/TSscheduling/tabs/InspectionScheduleTab.vue': {
      routes: '/Admin/OPAM/TSscheduling/tabs/InspectionScheduleTab'
      views: never
    }
    'src/pages/Admin/OPAM/TSscheduling/TSdashboard.vue': {
      routes: '/Admin/OPAM/TSscheduling/TSdashboard'
      views: never
    }
    'src/pages/Admin/OPAM/TSscheduling/TSinspection.vue': {
      routes: '/Admin/OPAM/TSscheduling/TSinspection'
      views: never
    }
    'src/pages/auth/Login.vue': {
      routes: '/auth/Login'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
