/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Admin/BPAM/Administrative': RouteRecordInfo<'/Admin/BPAM/Administrative', '/Admin/BPAM/Administrative', Record<never, never>, Record<never, never>>,
    '/Admin/CMM/Compliance': RouteRecordInfo<'/Admin/CMM/Compliance', '/Admin/CMM/Compliance', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/AAverification/AAchecklist': RouteRecordInfo<'/Admin/OPAM/AAverification/AAchecklist', '/Admin/OPAM/AAverification/AAchecklist', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/AAverification/AAdashboard': RouteRecordInfo<'/Admin/OPAM/AAverification/AAdashboard', '/Admin/OPAM/AAverification/AAdashboard', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/BIinspection/BIdashboard': RouteRecordInfo<'/Admin/OPAM/BIinspection/BIdashboard', '/Admin/OPAM/BIinspection/BIdashboard', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/BIinspection/BIreport': RouteRecordInfo<'/Admin/OPAM/BIinspection/BIreport', '/Admin/OPAM/BIinspection/BIreport', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/BIinspection/CIdashboard': RouteRecordInfo<'/Admin/OPAM/BIinspection/CIdashboard', '/Admin/OPAM/BIinspection/CIdashboard', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/BIinspection/CIreport': RouteRecordInfo<'/Admin/OPAM/BIinspection/CIreport', '/Admin/OPAM/BIinspection/CIreport', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/TSscheduling/TSdashboard': RouteRecordInfo<'/Admin/OPAM/TSscheduling/TSdashboard', '/Admin/OPAM/TSscheduling/TSdashboard', Record<never, never>, Record<never, never>>,
    '/Admin/OPAM/TSscheduling/TSinspection': RouteRecordInfo<'/Admin/OPAM/TSscheduling/TSinspection', '/Admin/OPAM/TSscheduling/TSinspection', Record<never, never>, Record<never, never>>,
    '/auth/Login': RouteRecordInfo<'/auth/Login', '/auth/Login', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/Admin/BPAM/Administrative.vue': {
      routes: '/Admin/BPAM/Administrative'
      views: never
    }
    'src/pages/Admin/CMM/Compliance.vue': {
      routes: '/Admin/CMM/Compliance'
      views: never
    }
    'src/pages/Admin/OPAM/AAverification/AAchecklist.vue': {
      routes: '/Admin/OPAM/AAverification/AAchecklist'
      views: never
    }
    'src/pages/Admin/OPAM/AAverification/AAdashboard.vue': {
      routes: '/Admin/OPAM/AAverification/AAdashboard'
      views: never
    }
    'src/pages/Admin/OPAM/BIinspection/BIdashboard.vue': {
      routes: '/Admin/OPAM/BIinspection/BIdashboard'
      views: never
    }
    'src/pages/Admin/OPAM/BIinspection/BIreport.vue': {
      routes: '/Admin/OPAM/BIinspection/BIreport'
      views: never
    }
    'src/pages/Admin/OPAM/BIinspection/CIdashboard.vue': {
      routes: '/Admin/OPAM/BIinspection/CIdashboard'
      views: never
    }
    'src/pages/Admin/OPAM/BIinspection/CIreport.vue': {
      routes: '/Admin/OPAM/BIinspection/CIreport'
      views: never
    }
    'src/pages/Admin/OPAM/TSscheduling/TSdashboard.vue': {
      routes: '/Admin/OPAM/TSscheduling/TSdashboard'
      views: never
    }
    'src/pages/Admin/OPAM/TSscheduling/TSinspection.vue': {
      routes: '/Admin/OPAM/TSscheduling/TSinspection'
      views: never
    }
    'src/pages/auth/Login.vue': {
      routes: '/auth/Login'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
